platform:
  sepolicy_dirs:
    - device/google/coral-sepolicy

includes:
  - common.yml

filters:
  partitions:
    match:
      # TODO: add support for OTA firmware partitions
      - xbl
      - xbl_config
      - aop
      - tz
      - hyp
      - abl
      - keymaster
      - devcfg
      - qupfw
      - uefisecapp
      - msadp
      - logfs
      - modem

  dep_files:
    match:
      # Required by libOmxSwVencMpeg4
      - vendor/lib/libMpeg4SwEncoder.so
      - vendor/lib64/libMpeg4SwEncoder.so

      # Required by chre
      - vendor/lib/libsdsprpc.so
      - vendor/lib64/libsdsprpc.so

  overlay_keys:
    match:
      - com.android.systemui:integer/config_keyguardRefreshRate
