platform:
  sepolicy_dirs:
    - device/google/gs201-sepolicy

includes:
  - common.yml

filters:
  partitions:
    match:
      # TODO: add support for OTA firmware partitions
      - bl1
      - pbl
      - bl2
      - abl
      - bl31
      - tzsw
      - gsa
      - ldfw
      - modem
