# Minimal non-GMS builds for privacy

includes:
  # Pixel-exclusive features that need additional support
  - flipendo.yml

# TODO: Add more exclusions
filters:
  props:
    prefix:
      # SetupWizard
      - ro.setupwizard.
      - setupwizard.

  files:
    match:
      # Apps that crash without GMS
      - product/priv-app/CarrierServices/CarrierServices.apk
      - product/priv-app/EuiccGoogle/EuiccGoogle.apk

    prefix:
      # AiAi
      - product/priv-app/DeviceIntelligenceNetworkPrebuilt
      - product/priv-app/DevicePersonalizationPrebuilt

  overlay_keys:
    prefix:
      # System app delegation
      - android:string/config_default

      # Pixel SetupWizard
      - com.google.android.pixel.setupwizard

  overlay_values:
    substring:
      # AiAi
      - com.google.android.as
