# Enhanced battery prediction & history, adaptive charging, etc.
filters:
  files:
    match:
      - product/priv-app/TurboPrebuilt/TurboPrebuilt.apk

    prefix:
      - system_ext/priv-app/TurboAdapter/

  sepolicy_dirs:
    match:
      - hardware/google/pixel-sepolicy/turbo_adapter
