# Enhanced battery prediction & history, adaptive charging, etc.
filters:
  files:
    match:
      - product/priv-app/TurboPrebuilt/TurboPrebuilt.apk

  sepolicy_dirs:
    match:
      - hardware/google/pixel-sepolicy/turbo_adapter
