device:
  name: bluejay

platform:
  product_makefile: device/google/bluejay/aosp_bluejay.mk

  sepolicy_dirs:
    - device/google/bluejay-sepolicy

includes:
  - snippets/2021.yml

filters:
  overlay_files:
    match:
      # Workaround for aapt2 output parsing bug
      - HbmSVManager__auto_generated_rro_product.apk
