device:
  name: oriole

platform:
  product_makefile: device/google/raviole/aosp_oriole.mk

includes:
  - snippets/2021.yml

filters:
  overlay_files:
    match:
      # Workaround for aapt2 output parsing bug
      - HbmSVManager__auto_generated_rro_product.apk
