device:
  name: panther

platform:
  product_makefile: device/google/pantah/aosp_panther.mk

includes:
  - snippets/2022.yml

filters:
  overlay_files:
    match:
      # Workaround for aapt2 output parsing bug
      - HbmSVManager__auto_generated_rro_product.apk
