device:
  name: raven

platform:
  product_makefile: device/google/raviole/aosp_raven.mk

includes:
  - snippets/2021.yml

filters:
  files:
    match:
    - vendor/etc/displayconfig/display_id_4619827677550801152.xml
